image:
  repository: "ghcr.io/notaryproject/ratify-gatekeeper-provider"
  pullPolicy: IfNotPresent
  tag: "dev"

replicaCount: 1

executor:
  scopes: []
  concurrency: 3
notation:
  scopes: []
  trustedIdentities: []
  certs:
  # - provider: "inline"
  #   cert: "" # PEM encoded certificate, e.g. "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
  # - provider: "azurekeyvault" # use "azurekeyvault" to use Azure Key Vault
  #   vaultURL: "" # e.g. "https://my-key-vault.vault.azure.net/"
  #   clientID: "" # optional
  #   tenantID: "" # optional
  #   certificates:
  #     - name: "" # name of the certificate in Azure Key Vault
  #       version: "" # optional, if not provided, the latest version will be used
cosign:
  scopes: []
  certificateIdentity: ""
  certificateIdentityRegex: ""
  certificateOIDCIssuer: ""
  certificateOIDCIssuerRegex: ""
  ignoreTLog: false
  ignoreCTLog: false
  keys:
    # provider: "inline"
    # key: "" # PEM encoded public key  e.g. "-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----"
    # or
    # provider: "azurekeyvault" # use "azurekeyvault" to use Azure Key Vault
    # vaultURL: "" # e.g. "https://my-key-vault.vault.azure.net/"
    # clientID: "" # optional
    # tenantID: "" # optional
    # keys:
    #   - name: "" # name of the key in Azure Key Vault
    #     version: "" # optional, if not provided, the latest version will be used

stores:
  - scopes: []
    caBase64: "" # base64 encoded CA certificate, used for TLS verification, e.g. "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg=="
    caPem: "" # PEM encoded CA certificate, used for TLS verification, e.g. "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"
    # if both caBase64 and caPem are provided, caPem will be used
    credential:
      provider: "static"
      username: ""
      password: ""
    # provider: "azure" # use "azure" to use Azure Workload Identity
    # clientID: "" # optional
    # tenantID: "" # optional
provider:
  tls:
    crt: "" # crt used by ratify (httpserver), please provide your own crt
    key: "" # key used by ratify (httpserver), please provide your own key
    caCert: "" # CA crt used by ratify (httpserver), please provide your own CA crt
    disableCertRotation: false
  disableMutation: false
  disableCRDManager: false
  timeout:
    # timeout values must match gatekeeper webhook timeouts
    validationTimeoutSeconds: 5
    mutationTimeoutSeconds: 2

gatekeeper:
  namespace: "gatekeeper-system"

serviceAccount:
  create: true
  name: ratify-gatekeeper-provider-admin
  # annotations to add to the service account
  annotations:
    {}
    # add azure.workload.identity/client-id if using Azure Workload Identity
