name: publish-cosign-sample

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read

jobs:
  build-publish:
    name: "Build and publish cosign signed sample image"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Install cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

      - name: Get repo
        run: |
          echo "REPOSITORY=${{ env.REGISTRY }}/${{ github.repository }}" >> $GITHUB_ENV

      - name: Write signing key to disk
        run: 'echo "$KEY" > cosign.key'
        shell: bash
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Log in to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build sample images
        run: |
          docker build -t ${REPOSITORY}/cosign-image:signed-key https://github.com/wabbit-networks/net-monitor.git
          docker build --no-cache -t ${REPOSITORY}/cosign-image:signed-keyless https://github.com/wabbit-networks/net-monitor.git
          docker build --no-cache -t ${REPOSITORY}/cosign-image:unsigned https://github.com/wabbit-networks/net-monitor.git
      - name: Push images
        run: |
          docker push ${REPOSITORY}/cosign-image:signed-key
          docker push ${REPOSITORY}/cosign-image:signed-keyless
          docker push ${REPOSITORY}/cosign-image:unsigned
      - name: Sign image with cosign
        run: |
          cosign sign --yes --key cosign.key ${REPOSITORY}/cosign-image:signed-key
          cosign sign --yes ${REPOSITORY}/cosign-image:signed-keyless
